imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    environment:
        php:
            version: 7.1
    dependencies:
        before:
            -
                command: "mkdir build"

    tests:
        override:
            -
                # command: "phpunit --configuration .phpunit.xml"
                command: "vendor/bin/phpunit ---configuration .phpunit.xml --coverage-clover=build/coverage.clover"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
checks:
    php:
        code_rating: true
        duplication: true
