# imports:
#     - php
#         version: 7.1

filter:
    excluded_paths: [vendor/*, test/*]

build:
    environment:
        php:
            version: 7.1
    dependencies:
        before:
            -
                command: "mkdir build"

    tests:
        override:
            -
                command: "phpunit --configuration .phpunit.xml"
                coverage:
                    file: "build/coverage.clover"
                    format: "clover"
